-- work
CREATE TABLE Person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name varchar(100) NOT NULL UNIQUE,
                        year_of_born int NOT NULL
);

CREATE TABLE Book (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year_of_production int NOT NULL,
                      person_id int REFERENCES Person(id) ON DELETE SET NULL
);

-- not work
create table Person (
                        id int generated by default as identity primary key ,
                        p_full_name varchar not null unique,
                        p_year_born int not null
);

create table Book (
                      id int generated by default as identity primary key ,
                      b_title varchar(100) not null ,
                      b_author varchar(100) not null,
                      b_year_of_production int not null ,
                      b_person_id int references Person(id) on delete set null
);




